name: Test Project

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
    steps:
      - name: checkout repository code
        uses: actions/checkout@v1

      - name: Install Java JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 1.15
          
      - name: test the project and upload test report -> sonarqube
        run: ./gradlew test jacocoTestReport sonarqube --info

      - name: Build with Gradle
        run: ./gradlew build

      - name: Test with Gradle
        run: ./gradlew test
